### ISSUE TITLE
Hwyla Issue on 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [t2pellet/strawgolem#108]
```java
[01Oct2022 11:22:24.860] [Worker-Main-15/ERROR] [Waila/]: Error loading plugin at com.t2pellet.strawgolem.client.compat.ForgeCompatHwyla
java.lang.NoSuchMethodError: 'void mcp.mobius.waila.api.IRegistrar.addComponent(mcp.mobius.waila.api.IEntityComponentProvider, mcp.mobius.waila.api.TooltipPosition, java.lang.Class)'
	at com.t2pellet.strawgolem.client.compat.CompatHwyla.register(CompatHwyla.java:21) ~[Strawgolem-forge-1.18.2-2.0.0b2.jar%23370!/:2.0.0b2]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:114) ~[Jade-1.18.2-forge-5.2.4.jar%23225!/:5.2.4]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23423!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23422!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by t2pellet** [comment]
HWYLA isn't updated for 1.18.2

WTHIT is though. From what I see, even using the latest WTHIT there's no problem. Can you show me what version of strawgolem and wthit/hwyla/waila you're using?

**Comment by t2pellet** [comment]
Are you using Jade? if so, why Jade over WTHIT - are there distinct advantages?

Genuine question, haven't been keeping up with mods for a while
