### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Mosca42** [t2pellet/strawgolem#120]
Version : 1.18.2-2.0.0 beta 3

Error : 
[07déc.2022 21:53:59.147] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23107!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:338) ~[?:?]
	at java.util.HashMap.put(HashMap.java:610) ~[?:?]
	at com.t2pellet.strawgolem.util.struct.OctTree.<init>(OctTree.java:175) ~[Strawgolem-forge-1.18.2-2.0.0-beta.3.jar%2398!/:2.0.0-beta.3]
	at com.t2pellet.strawgolem.util.struct.OctTree.insert(OctTree.java:203) ~[Strawgolem-forge-1.18.2-2.0.0-beta.3.jar%2398!/:2.0.0-beta.3]
	at com.t2pellet.strawgolem.util.struct.OctTree.insert(OctTree.java:206) ~[Strawgolem-forge-1.18.2-2.0.0-beta.3.jar%2398!/:2.0.0-beta.3]
	at com.t2pellet.strawgolem.util.struct.OctTree.insert(OctTree.java:206) ~[Strawgolem-forge-1.18.2-2.0.0-beta.3.jar%2398!/:2.0.0-beta.3]
	at com.t2pellet.strawgolem.util.struct.OctTree.insert(OctTree.java:206) ~[Strawgolem-forge-1.18.2-2.0.0-beta.3.jar%2398!/:2.0.0-beta.3]
	
	
	
	(this.children ? )

**Comment by t2pellet** [comment]
Is this a crash on startup or just at some point while the server was on?

**Comment by Mosca42** [comment]
on a world generation, your package struct = structure ?

**Comment by patykin** [comment]
Error persists

**Comment by t2pellet** [comment]
With the latest upload here and on curseforge? Note its the same versioning as the last one, but it was reuploaded last night
