### ISSUE TITLE
2.0.0A1 Crash "Invalid Java Runtime Configuration"

### ISSUE THREAD

**Issue by Freshah** [t2pellet/strawgolem#73]
`[11May2022 21:25:51.474] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Freshah, --version, 1.18.2-forge-40.0.45, --gameDir, D:\other downloads\SepulcherINDEV, --assetsDir, C:\Users\Anderson\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 5bd642df46404f84bc5750e7dad39a39, --accessToken, ????????, --clientId, MmEzMjJhNGEtZDM3Mi00ZDUyLWI5ZGYtZjgyNWQ0OWRmNTc0, --xuid, 2535436328304236, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.0.45, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[11May2022 21:25:51.480] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[11May2022 21:25:51.681] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Anderson/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[11May2022 21:25:55.032] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[11May2022 21:25:55.062] [main/ERROR] [mixin/]: Mixin config biomemakeover-common.mixins.json does not specify "minVersion" property
[11May2022 21:25:55.066] [main/ERROR] [mixin/]: Mixin config biomemakeover-forge.mixins.json does not specify "minVersion" property
[11May2022 21:25:55.386] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.sonicether.soundphysics.MixinConnector]
[11May2022 21:25:55.387] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[11May2022 21:25:55.398] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.0.45, --gameDir, D:\other downloads\SepulcherINDEV, --assetsDir, C:\Users\Anderson\AppData\Roaming\.minecraft\assets, --uuid, 5bd642df46404f84bc5750e7dad39a39, --username, Freshah, --assetIndex, 1.18, --accessToken, ????????, --clientId, MmEzMjJhNGEtZDM3Mi00ZDUyLWI5ZGYtZjgyNWQ0OWRmNTc0, --xuid, 2535436328304236, --userType, msa, --versionType, release]
[11May2022 21:25:55.501] [main/WARN] [mixin/]: Reference map 'farmersrespite.refmap.json' for farmersrespite.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:55.513] [main/WARN] [mixin/]: Reference map 'heartstone.refmap.json' for heartstone.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:55.540] [main/WARN] [mixin/]: Reference map 'nethersdelight.refmap.json' for nethersdelight.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:55.545] [main/WARN] [mixin/]: Reference map 'overweightfarming.refmap.json' for overweightfarming.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:55.558] [main/WARN] [mixin/]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:55.681] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:55.683] [main/WARN] [mixin/]: Reference map 'yungsextras.refmap.json' for yungsextras_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[11May2022 21:25:56.402] [main/WARN] [mixin/]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
[11May2022 21:25:56.907] [main/WARN] [mixin/]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
[11May2022 21:25:56.907] [main/WARN] [mixin/]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
[11May2022 21:25:56.918] [main/INFO] [ModdingLegacy/Lucent/]: [lucent] Optifine not detected
[11May2022 21:25:57.957] [pool-3-thread-1/WARN] [mixin/]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zfg000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[11May2022 21:25:58.293] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed strawgolem.forge.mixins.json:GrowthMixin -> net.minecraft.world.level.Level: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on grow could not find any targets matching 'setBlock' in net.minecraft.world.level.Level. No refMap loaded. [PREINJECT Applicator Phase -> strawgolem.forge.mixins.json:GrowthMixin -> Prepare Injections ->  -> handler$beh000$grow(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on grow could not find any targets matching 'setBlock' in net.minecraft.world.level.Level. No refMap loaded. [PREINJECT Applicator Phase -> strawgolem.forge.mixins.json:GrowthMixin -> Prepare Injections ->  -> handler$beh000$grow(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.GeneratedConstructorAccessor63.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:123) ~[forge-1.18.2-40.0.45-universal.jar%23162!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:108) ~[forge-1.18.2-40.0.45-universal.jar%23162!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23158!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:391) ~[client-1.18.2-20220404.173914-srg.jar%23158!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:170) ~[client-1.18.2-20220404.173914-srg.jar%23158!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%23158!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23158!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

The exit code tells players that something is wrong with Minecraft's bundled Javaw

**Comment by t2pellet** [comment]
Mixin problem, will look at and fix tom

**Comment by Freshah** [comment]
no rush friend.  thank you!

**Comment by t2pellet** [comment]
Should be fixed with latest commit
