### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by WildStrawb** [t2pellet/strawgolem#77]
_This is my first bug report on GitHub so I appreciate your patience. Aplogies if this ends up being a mod comp issue or something else on my end._

**Summary:**
Mod File: strawgolem-1.16-1.9.jar
	Failure message: Straw Golem (strawgolem) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/common/capabilities/Capability$IStorage
	Mod Version: 1.16-1.9
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.capabilities.Capability$IStorage

**Details:**
Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/common/capabilities/Capability$IStorage
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
		at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
		at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.0.jar%2367!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.0.jar%2366!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

Thanks! Love the mod, the golems are so adorable.

**Comment by t2pellet** [comment]
You're using a 1.16 version of the mod for 1.18.

You can find a 1.18 download here:
https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn/files/3790160

**Comment by WildStrawb** [comment]
Wow, I'm absolutely mortified I mixed up the previous file with the new
download, thank you!
___________________
Logan A. Barrick
(717) 357 - 6382
***@***.***
