### ISSUE TITLE
1.18.2 Straw Golem Summon Crash

### ISSUE THREAD

**Issue by VeryTimmy** [t2pellet/strawgolem#83]
**Game Info**
Game Version : 1.18.2
Mod Version : 1.18.2
Mod Loader : Forge 40.1.20

**Describe the bug**
I just summoned a straw golem and server crashed immediately

**To Reproduce**

1. Place a haybale
2. Place a 
3. A straw golem spawned
4. Server closed immediately
5. Go to the server console
6. See error

**Screenshots**

**Additional context**
Error text (console):
[14:04:09] [Server thread/ERROR] [ne.mi.ne.si.IndexedMessageCodec/SIMPLENET]: Received invalid message com.t2pellet.strawgolem.network.HealthPacket on channel strawgolem:main
[14:04:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B}
at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.IllegalArgumentException: Invalid message com.t2pellet.strawgolem.network.HealthPacket
at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:131) ~[forge-1.18.2-40.1.19-universal.jar%2363!/:?] {re:classloading}
at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:73) ~[forge-1.18.2-40.1.19-universal.jar%2363!/:?] {re:classloading}
at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:86) ~[forge-1.18.2-40.1.19-universal.jar%2363!/:?] {re:classloading}
at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:117) ~[forge-1.18.2-40.1.19-universal.jar%2363!/:?] {re:classloading}
at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:112) ~[forge-1.18.2-40.1.19-universal.jar%2363!/:?] {re:classloading}
at com.t2pellet.strawgolem.platform.ForgePacketHandler.sendTo(ForgePacketHandler.java:78) ~[Strawgolem-forge-1.18.2-2.0.0a2.jar%2355!/:2.0.0a2] {re:classloading}
at com.t2pellet.strawgolem.platform.ForgePacketHandler.sendTo(ForgePacketHandler.java:84) ~[Strawgolem-forge-1.18.2-2.0.0a2.jar%2355!/:2.0.0a2] {re:classloading}
at com.t2pellet.strawgolem.platform.ForgePacketHandler.sendInArea(ForgePacketHandler.java:97) ~[Strawgolem-forge-1.18.2-2.0.0a2.jar%2355!/:2.0.0a2] {re:classloading}
at com.t2pellet.strawgolem.platform.ForgePacketHandler.sendInRange(ForgePacketHandler.java:90) ~[Strawgolem-forge-1.18.2-2.0.0a2.jar%2355!/:2.0.0a2] {re:classloading}
at com.t2pellet.strawgolem.entity.EntityStrawGolem.m_6075_(EntityStrawGolem.java:132) ~[Strawgolem-forge-1.18.2-2.0.0a2.jar%2355!/:2.0.0a2] {re:mixin,re:classloading}
at net.minecraft.world.entity.Entity.m_8119_(Entity.java:413) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2215) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,re:mixin}
at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:A}
at net.minecraft.world.level.Level.m_46653_(Level.java:486) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.forge.mixins.json:GrowthMixin,pl:mixin:A}
at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:A}
at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading}
at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%2359!/:?] {re:classloading,pl:accesstransformer:B}
... 5 more
[14:04:09] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 34c1b256-e793-4e7b-856a-94598393b253
[14:04:09] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /server/server-data/./crash-reports/crash-2022-05-23_14.04.09-server.txt

**Comment by t2pellet** [comment]
I'm guessing this only occurs on a dedicated server?

**Comment by ThugPug43** [comment]
I encountered this same issue on a dedicated server.

**Comment by ThugPug43** [comment]
[crash-2022-05-31_22.23.44-server.txt](https://github.com/t2pellet/strawgolem/files/8810839/crash-2022-05-31_22.23.44-server.txt)

**Comment by t2pellet** [comment]
So it occurs in a singleplayer world as well?

**Comment by d0ubleJ** [comment]
@VeryTimmy This seems to be due to an incompatibility with Quark Mods in general.  The issue was noted in a previous issue, and I suspect that is your problem.

**Comment by t2pellet** [comment]
Should be fixed in latest curseforge release (2.0.0a3). Please reopen if it isn't
