### ISSUE TITLE
Mod won't load 1.18.2 - no recipes in JEI

### ISSUE THREAD

**Issue by ncottrill** [t2pellet/strawgolem#93]
**Game Info**
Game Version : 1.18.2
Mod Version : Strawgolem-forge-1.18.2-2.0.0b1
Mod Loader : Forge

**Describe the bug**
Installed mod in the /mods/ folder. Mod and its contents do not load.

**To Reproduce**
1) Put strawgolem-forge*.jar in the /mods/ folder
2) Start game
3) No straw golem content

**Screenshots**

**Additional context**

Log lines mentioning strawgolem mod

[18:53:09] [Worker-Main-28/WARN]: File strawgolem:sounds/strawgolem-disgusted.ogg does not exist, cannot add it to event strawgolem:golem_disgusted
[18:53:11] [Worker-Main-30/INFO]: [OptiFine] Scaled non power of 2: strawgolem:particle/fly, 3 -> 9
[18:53:40] [Worker-Main-19/INFO]: Start loading plugin at com.t2pellet.strawgolem.client.compat.ForgeCompatHwyla
[18:53:40] [Worker-Main-19/INFO]: Registering Strawgolem HWYLA Compat
[18:53:40] [Worker-Main-19/ERROR]: Error loading plugin at com.t2pellet.strawgolem.client.compat.ForgeCompatHwyla
java.lang.NoSuchMethodError: 'void mcp.mobius.waila.api.IRegistrar.addComponent(mcp.mobius.waila.api.IEntityComponentProvider, mcp.mobius.waila.api.TooltipPosition, java.lang.Class)'
	at com.t2pellet.strawgolem.client.compat.CompatHwyla.register(CompatHwyla.java:21) ~[Strawgolem-forge-1.18.2-2.0.0b1.jar%23157!/:2.0.0b1]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:114) ~[Jade-1.18.2-forge-5.2.2.jar%23123!/:5.2.2]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
[18:55:08] [Netty Client IO #0/ERROR]: Channels [minecolonies:net-channel,strawgolem:main] rejected their server side version number during listping
[18:55:08] [Netty Client IO #0/INFO]: Server has additional mods that may be needed on the client: perf@
[18:55:08] [Netty Client IO #0/INFO]: Client has mods that are missing on server: [alexsmobs, strawgolem, sophisticatedcore, sophisticatedbackpacks, structure_gel, curios, patchouli, blockui, architectury, mcwfurnitures, geckolib3, jei, awesomedungeon, naturescompass, ars_nouveau, ecologics, minecolonies, chiselsandbits]
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_ambient Expected: 1203 Got: 1401
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_strained Expected: 1204 Got: 1437
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_hurt Expected: 1205 Got: 1438
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_death Expected: 1206 Got: 1439
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_heal Expected: 1207 Got: 1440
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_scared Expected: 1208 Got: 1453
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_interested Expected: 1209 Got: 1459
[18:55:18] [Render thread/WARN]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: strawgolem:golem_disgusted Expected: 1210 Got: 1460
[18:55:18] [Render thread/WARN]: Registry minecraft:entity_type: Object did not get ID it asked for. Name: strawgolem:strawgolem Expected: 113 Got: 453
[18:55:18] [Render thread/WARN]: Registry minecraft:entity_type: Object did not get ID it asked for. Name: strawgolem:strawnggolem Expected: 114 Got: 454

**Comment by ncottrill** [comment]
There isn't a recipe for JEI! LOL. I watched video and then was able to create a straw golem right in the world. So, closing this. Maybe some of the warnings above will be relevant to you for something else.
